name: Release Application

permissions:
  contents: write

on:
  push:
    branches:
     - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'ObjectTracking.spec'
        requirements: 'requirements.txt'
        python_ver: '3.11.8'
        python_arch: 'x64'
        clean_checkout: 'false'

    - name: Create Executable (NoConsole)
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'ObjectTracking_NoConsole.spec'
        requirements: 'requirements.txt'
        python_ver: '3.11.8'
        python_arch: 'x64'
        clean_checkout: 'false'

    - name: zip Application
      uses: montudor/action-zip@v1
      with:
        args: zip -r ObjectTracking.zip dist/ObjectTracking/

    - name: zip Application (NoConsole)
      uses: montudor/action-zip@v1
      with:
        args: zip -r ObjectTracking_NoConsole.zip dist/ObjectTracking_NoConsole/

    - name: Make Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ObjectTracking.zip
          ObjectTracking_NoConsole.zip
        tag_name: "v0.0.0"